pipeline {
agent any
 
tools{
maven 'maven3.6.0'
jdk 'java1.8.0'
}
 
stages {
stage ('build') {
 steps {
  sh "mvn -B -DskipTests clean package"
 }
}
     
stage('Test') {
   steps {
     sh "mvn test"
   }
   post{
     always{
       junit 'target/surefire-reports/*.xml'
     }
   }
 }
 /*stage('SonarQube analysis') {
     steps{
    withSonarQubeEnv('sonar') {
      sh 'mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.2:sonar'
    }
     }
  }*/
}
}
