pipeline {
agent any
 
tools{
maven 'maven3.6.0'
jdk 'java1.8.0'
}
 
stages {
stage ('build') {
 steps {
  sh "mvn -B -DskipTests clean package"
 }
}
     
stage('Test') {
   steps {
     sh "mvn test"
   }
   post{
     always{
       junit 'target/surefire-reports/*.xml'
     }
   }
 }
 stage('Deploy'){
  steps{
     //sh 'java -jar target/my-app-1.0-SNAPSHOT.jar'
   sh 'scp -o StrictHostKeyChecking=no -i /tmp/Mars.pem target/my-app-1.0-SNAPSHOT.jar centos@54.201.149.191:/tmp/'
   sh 'ssh -i /tmp/Mars.pem centos@54.201.149.191 java -jar /tmp/my-app-1.0-SNAPSHOT.jar'
  }
 }
}
}
